/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import thread.ThreadTimer;

/**
 *
 * @author Darko
 */
public class FrmMain extends javax.swing.JFrame {

    int homeScore;
    int awayScore;
    int homeTimeouts;
    int awayTimeouts;
    ThreadTimer tt;

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        atStart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMainTimer = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        lblAway = new javax.swing.JLabel();
        lblHomeScore = new javax.swing.JLabel();
        lblAwayScore = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblHomeTimeout = new javax.swing.JLabel();
        lblAwayTimeout = new javax.swing.JLabel();
        btnHomeTimeout = new javax.swing.JButton();
        btnAwayTimeout = new javax.swing.JButton();
        lblTimeoutTimer = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        btnHomePlus = new javax.swing.JButton();
        btnHomeMinus = new javax.swing.JButton();
        btnAwayMinus = new javax.swing.JButton();
        btnAwayPlus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scoreboard");

        lblMainTimer.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        lblMainTimer.setText("10:00");

        lblHome.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblHome.setText("Home");

        lblAway.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblAway.setText("Away");

        lblHomeScore.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblHomeScore.setText("0");

        lblAwayScore.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblAwayScore.setText("0");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Timeouts");

        lblHomeTimeout.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblHomeTimeout.setText("3");

        lblAwayTimeout.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblAwayTimeout.setText("3");

        btnHomeTimeout.setText("Take timeout");
        btnHomeTimeout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeTimeoutActionPerformed(evt);
            }
        });

        btnAwayTimeout.setText("Take timeout");
        btnAwayTimeout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayTimeoutActionPerformed(evt);
            }
        });

        lblTimeoutTimer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTimeoutTimer.setText(":59");

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnStop.setText("STOP");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        btnHomePlus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHomePlus.setText("+");
        btnHomePlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePlusActionPerformed(evt);
            }
        });

        btnHomeMinus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHomeMinus.setText("-");
        btnHomeMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeMinusActionPerformed(evt);
            }
        });

        btnAwayMinus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAwayMinus.setText("-");
        btnAwayMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayMinusActionPerformed(evt);
            }
        });

        btnAwayPlus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAwayPlus.setText("+");
        btnAwayPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAwayPlusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblHome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblHomeScore)))
                .addGap(231, 231, 231)
                .addComponent(lblMainTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblAway)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblAwayScore)
                        .addGap(48, 48, 48))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addComponent(btnHomeTimeout))
                            .addComponent(btnHomePlus, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHomeMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(290, 290, 290)
                        .addComponent(btnStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(btnAwayTimeout)
                .addGap(198, 198, 198)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAwayPlus, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(btnAwayMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(lblHomeTimeout)
                .addGap(87, 87, 87)
                .addComponent(lblTimeoutTimer)
                .addGap(90, 90, 90)
                .addComponent(lblAwayTimeout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAway)
                        .addGap(18, 18, 18)
                        .addComponent(lblAwayScore))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHome)
                        .addGap(18, 18, 18)
                        .addComponent(lblHomeScore))
                    .addComponent(lblMainTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btnHomeTimeout)
                            .addComponent(btnAwayTimeout))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHomeTimeout)
                            .addComponent(lblAwayTimeout)
                            .addComponent(lblTimeoutTimer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnHomePlus, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHomeMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAwayPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAwayMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomePlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePlusActionPerformed
        lblHomeScore.setText(Integer.toString(++homeScore));
    }//GEN-LAST:event_btnHomePlusActionPerformed

    private void btnHomeMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeMinusActionPerformed
        lblHomeScore.setText(Integer.toString(--homeScore));
    }//GEN-LAST:event_btnHomeMinusActionPerformed

    private void btnAwayPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayPlusActionPerformed
        lblAwayScore.setText(Integer.toString(++awayScore));
    }//GEN-LAST:event_btnAwayPlusActionPerformed

    private void btnAwayMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayMinusActionPerformed
        lblAwayScore.setText(Integer.toString(--awayScore));
    }//GEN-LAST:event_btnAwayMinusActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        homeScore = 0;
        awayScore = 0;
        homeTimeouts = 4;
        awayTimeouts = 4;
        updateUI();

        tt = new ThreadTimer(lblMainTimer, true);
        tt.start();

        btnStop.setVisible(true);
        btnStart.setVisible(false);
        enableButtons();
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        if (tt.isRun()) {
            tt.setRun(false);
        }
        btnStop.setVisible(false);
        btnStart.setVisible(true);
        disableButtons();
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnHomeTimeoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeTimeoutActionPerformed
        // TODO
    }//GEN-LAST:event_btnHomeTimeoutActionPerformed

    private void btnAwayTimeoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAwayTimeoutActionPerformed
        // TODO
    }//GEN-LAST:event_btnAwayTimeoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAwayMinus;
    private javax.swing.JButton btnAwayPlus;
    private javax.swing.JButton btnAwayTimeout;
    private javax.swing.JButton btnHomeMinus;
    private javax.swing.JButton btnHomePlus;
    private javax.swing.JButton btnHomeTimeout;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAway;
    private javax.swing.JLabel lblAwayScore;
    private javax.swing.JLabel lblAwayTimeout;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblHomeScore;
    private javax.swing.JLabel lblHomeTimeout;
    private javax.swing.JLabel lblMainTimer;
    private javax.swing.JLabel lblTimeoutTimer;
    // End of variables declaration//GEN-END:variables

    private void atStart() {
        updateUI();
        btnStop.setVisible(false);
        disableButtons();
    }

    private void disableButtons() {
        btnHomePlus.setEnabled(false);
        btnHomeMinus.setEnabled(false);
        btnAwayPlus.setEnabled(false);
        btnAwayMinus.setEnabled(false);

        btnHomeTimeout.setEnabled(false);
        btnAwayTimeout.setEnabled(false);
    }

    private void enableButtons() {
        btnHomePlus.setEnabled(true);
        btnAwayPlus.setEnabled(true);
        btnHomeMinus.setEnabled(true);
        btnAwayMinus.setEnabled(true);

        // Timeouts for TODO
        // btnHomeTimeout.setEnabled(true);
        // btnAwayTimeout.setEnabled(true);
    }

    private void updateUI() {
        lblHomeTimeout.setText(Integer.toString(homeTimeouts));
        lblAwayTimeout.setText(Integer.toString(awayTimeouts));

        lblHomeScore.setText(Integer.toString(homeScore));
        lblAwayScore.setText(Integer.toString(awayScore));
    }
}
